language: perl
dist: xenial
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
# Whitelist branches for CI, ignore all other branches
branches:
  only:
    - addusergroup
env:
  global:
    - "HARNESS_OPTIONS=j9"
    - "cpanm -n --installdeps ."

matrix:
  allow_failures:
    - TEST_AUTHOR=1
  fast_finish: true
  include:
    - "TEST_AUTHOR=1"
      "cpanm -n Test::Perl::Critic Test::Pod"
      "5.22"

notifications:
  email: false
sudo: false
