language: perl
dist: xenial
perl:
  - "5.28"
  - "5.26"
env:
  global:
    - "HARNESS_OPTIONS=j9"
    - "cpanm -n --installdeps ."
  matrix:
    - TEST_AUTHOR=1
    - TEST_AUTHOR=0
matrix:
  allow_failures:
    - TEST_AUTHOR=1
  fast_finish: true
notifications:
  email: false

