language: perl
dist: xenial
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
# Whitelist branches for CI, ignore all other branches
branches:
  only:
    - master
notifications:
  email: false
sudo: false
env:
  global:
    - HARNESS_OPTIONS=j9
  matrix:
    - TEST_AUTHOR=1
    - TEST_AUTHOR=0
before_install:
  - "cpanm -n Test::Pod Test::Perl::Critic"
install:
  - cpanm -n --installdeps .
