#!perl
use strict;
use warnings;
use FindBin qw($Bin);
use Cwd qw(abs_path);
use lib ();

BEGIN {
  for ("$Bin/../local/lib/perl5", "$Bin/../lib/perl5", "$Bin/../lib", "$Bin/../site/lib")
  {
    lib->import(abs_path $_) if (-d $_);
  }
}

use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Slovo');

